### ISSUE TITLE
plv stopped logging after pacman update

### ISSUE THREAD

**Issue by kinoegit** [gcala/pacmanlogviewer#3] opened 2019-11-19 12:14 UTC
Hello and thank you for your tool. It is helping me to watch pacman log in a simple an straightforward way!
Unfortunately it ceased to display /var/log/pacman.log when pacman was upgraded: pacman (5.1.3-1 -> 5.2.0-2) in October 23. Since that date pacman logs differently:
formerly `[2019-10-23 14:10] .....`
after update `[2019-10-23T14:52:38+0200] .....`
Default log or custom log to /var/log/pacman.log makes no difference.

**Comment by kinoegit** [comment] 2019-11-21 05:14
Thanks for updating. Its running well again :)

**Comment by jjgalvez** [comment] 2019-11-29 21:37
has this been fixed? I built this from the latest source and it still has the same issue as originally described. It can no longer read the log past Oct 23

**Comment by kinoegit** [comment] 2019-11-30 05:43
No issues here anymore since last update

**Comment by muflone** [comment] 2019-11-30 14:43
Some Manjaro users reported me issues with Arch Linux package, however cannot tell you the details.

I only package and support Arch Linux, not derived distributions.

**Comment by jjgalvez** [comment] 2019-11-30 20:34
I did a fresh arch install in a VM and PLV worked there, so obviously it's something on my machine. are there any logs or any way to trouble shoot this. I've checked all the dependencies and they are all accounted for.

**Comment by muflone** [comment] 2019-11-30 22:51
You have to inspect the pacman.log file format, if it contains weird information or the content uses a different format

In the case you're able to solve, please attach your (not working) pacman.log file

**Comment by jjgalvez** [comment] 2019-12-02 01:19
The log file does not look any different between the two machines

**Comment by muflone** [comment] 2019-12-02 12:32
Try to empty it.
Maybe some old entry confuses it

My 2011 pacman.log is ok though

**Comment by yochananmarqos** [comment] 2019-12-05 20:38
@muflone I think I figured it out. I was one of the Manjaro users who emailed you about it. This is the line right after the last line available in `plv`:
```
[2019-10-25 08:35] [ALPM-SCRIPTLET] [1;1m[1;32m==>[1;0m[1;1m Printing support installed[1;0m
```

I have the `Color` option enabled in `/etc/pacman.conf`, could that be it? Are those escaped color characters?

**Comment by muflone** [comment] 2019-12-05 21:10
> ```
> [2019-10-25 08:35] [ALPM-SCRIPTLET] �[1;1m�[1;32m==>�[1;0m�[1;1m Printing support installed�[1;0m
> ```

What package produced that output in pacman.log?
My pacman.log file is still clean even after enabling Color in pacman.conf

**Comment by yochananmarqos** [comment] 2019-12-05 21:26
Found it:
```
[2019-11-01T08:29:40-0600] [ALPM] running 'manjaro-gnome-messages.hook'...
[2019-11-01T08:29:40-0600] [ALPM-SCRIPTLET] 
[2019-11-01T08:29:40-0600] [ALPM-SCRIPTLET] [1;1m[1;32m==>[1;0m[1;1m Printing support installed[1;0m
```

`/usr/share/libalpm/scripts/manjaro-gnome-messages`
```
#!/bin/sh

## Colored message

msg() {
ALL_OFF="\e[1;0m"
BOLD="\e[1;1m"
GREEN="${BOLD}\e[1;32m"
local mesg=$1; shift
printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" "$@" >&2
}
 
## Symple script to check if printing support is installed

if pacman -Qi cups > /dev/null 2>&1; then
   echo ""
   msg "Printing support installed"
   echo ""
else 
   echo ""
   msg "Printing support not installed, to enable please type this in a terminal:
	 -> sudo pacman -S manjaro-printer
	 -> or install manjaro-printer pkg via pamac"
   echo ""
fi
```
There's a few more scripts like that, too.

**Comment by muflone** [comment] 2019-12-05 23:11
As usual, Manjaro break things.
If @gcala desires to introduce support for Manjaro, a better parsing for special characters is needed.

From the Arch Linux side, there's nothing I can do for you @yochananmarqos, until the issue can be reproduced in Arch Linux.

@jjgalvez do you used Color in pacman.conf and your pacman.log contains weird formatting symbols?

**Comment by jjgalvez** [comment] 2019-12-05 23:33
no there is nothing odd looking in my pacman.conf and no color. At this point I will likely stop using it because its just not reporting any errors, just not working  so it makes it very difficult if not impossible to help debug this

**Comment by rafikdraoui** [comment] 2019-12-15 23:14
This also happens for me on an Arch Linux system. It turns out that the problem is caused by me being in the Western hemisphere: my timestamps are of the form `2019-12-15T17:58:15-0500`, but the regex only consider times with a positive UTC offset :smiley: 

When I load the following log (through the "Load custom log" item in the top right menu), nothing shows in the viewer:

```
[2019-12-15T17:58:15-0500] [PACMAN] Running 'pacman -Syu'
[2019-12-15T17:58:15-0500] [PACMAN] synchronizing package lists
[2019-12-15T17:58:16-0500] [PACMAN] starting full system upgrade
[2019-12-15T17:58:26-0500] [PACMAN] Running 'pacman -R pacmanlogviewer'
[2019-12-15T17:58:27-0500] [ALPM] transaction started
[2019-12-15T17:58:27-0500] [ALPM] removed pacmanlogviewer (1.4.1-1)
[2019-12-15T17:58:27-0500] [ALPM] transaction completed
[2019-12-15T17:58:27-0500] [ALPM] running '30-systemd-update.hook'...
[2019-12-15T17:58:27-0500] [ALPM] running 'gtk-update-icon-cache.hook'...
[2019-12-15T17:58:27-0500] [ALPM] running 'update-desktop-database.hook'...
[2019-12-15T17:58:35-0500] [PACMAN] Running 'pacman -S pacmanlogviewer'
[2019-12-15T17:58:37-0500] [ALPM] transaction started
[2019-12-15T17:58:37-0500] [ALPM] installed pacmanlogviewer (1.4.1-1)
[2019-12-15T17:58:37-0500] [ALPM] transaction completed
[2019-12-15T17:58:37-0500] [ALPM] running '30-systemd-update.hook'...
[2019-12-15T17:58:37-0500] [ALPM] running 'gtk-update-icon-cache.hook'...
[2019-12-15T17:58:37-0500] [ALPM] running 'update-desktop-database.hook'...
```

But if I change the timestamps to something like `2019-12-15T17:58:15+0200` then it works fine.

(cc @gcala @jjgalvez )

**Comment by gcala** [comment] 2019-12-21 17:19
@rafikdraoui sorry for my delayed response and for the offset inconvenience. ~~Just uploaded a fix~~ merged @chrisjbillington pull request, can you test and report back? thanks

**Comment by rafikdraoui** [comment] 2019-12-21 19:09
It works for me, thanks!

**Comment by jjgalvez** [comment] 2019-12-21 19:21
works for me too now! thank you

**Comment by yochananmarqos** [comment] 2019-12-21 19:37
Works for me as well, thanks!

**Closed as completed** 2020-01-03 11:17 UTC

**Comment by jjgalvez** [comment] 2020-01-09 13:34
I know this is already closed, just wanted to also confirm that the fix works for me as well and thank you
